name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore /home/runner/work/B3-Desafio-Cdb/B3-Desafio-Cdb/calculadora-cdb.sln
    - name: Build
      run: dotnet build --no-restore /home/runner/work/B3-Desafio-Cdb/B3-Desafio-Cdb/calculadora-cdb.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal /home/runner/work/B3-Desafio-Cdb/B3-Desafio-Cdb/calculadora-cdb.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}